// Embeds src/tokens.css into src/tokens.generated.ts so the library can install the tokens at
// runtime without a CSS import step. The generated file is committed and checked by a test.
import { readFileSync, writeFileSync } from 'node:fs';

const css = readFileSync(new URL('../src/tokens.css', import.meta.url), 'utf8');
const out = `// Generated by scripts/sync-tokens.mjs from tokens.css. Do not edit.\nexport const tokensCss: string = ${JSON.stringify(css)};\n`;
writeFileSync(new URL('../src/tokens.generated.ts', import.meta.url), out);
